### ISSUE TITLE
Zanavi uses drive throughs while on freeway

### ISSUE THREAD

**Issue by mauritslamers** [zoff99/zanavi#1]
While driving on the freeway, Zanavi sometimes indicates that an exit should be taken, and then it leads back to the same freeway using the drivethrough. I haven't experienced this in earlier versions of Zanavi. I don't know whether this is due to something in the maps or Zanavi itself, but it is a bit annoying.
Perhaps the route building takes this "shortcut" because it is a very little bit shorter?

This is one spot where it happened: https://www.openstreetmap.org/#map=16/49.4434/8.3278, driving south.

Using Zanavi v2.0.44 on a Samsung S3 mini with the most recent maps.

**Comment by zoff99** [comment]
this should be fixed in 2.0.49
