### ISSUE TITLE
Map switzerland can´t be downloaded

### ISSUE THREAD

**Issue by ghtux** [zoff99/zanavi#16]
#### Your system information:
ZANavi Version: 2.0.56

App from Google-Play / F-Droid / other: F-Droid

Android OS Version: 6.01

Device: Galaxy S5

I tried to download the map for switzerland several times. Map size is about 145 MB. It starts downloading more than 500 mb and afterwards it quits because of md5 mismatch. Tried wlan and mobile connection. Other maps can be downloaded as expected.

**Comment by zoff99** [comment]
i see the index file is missing on one of the mapserver. i am sorry about that. will try to upload today.
if you try a couple of time you should get to another server for the index. how often have you tried?
can you attach the debug log (with: "Menu" -> "About" -> "send crashreport via email") ?

**Comment by ghtux** [comment]
You got mail :-) several debug_downloads for switzerland in the log.

**Comment by ghtux** [comment]
The problem is proxy related. Without using a proxy all downloads are fine. So it´s not a direct zanavi problem.
