### ISSUE TITLE
Download Index File fails

### ISSUE THREAD

**Issue by ghost** [zoff99/zanavi#22]
﻿#### Your system information:
ZANavi Version: 2.0.57

App from Google-Play / F-Droid / other: F-Droid

Android OS Version: 6.0.1

Device: Samsung Galaxy S5 Cat 6

#### Please describe your issue in as much detail as possible:
Everytime ZANavi tries to download the index file, an error occurrences "Can't download index file" or something like this. 

#### Steps for reproducing this issue:
Fresh installation:
- Select SD Card (with enough space!)
- Select Germany
- Click "OK"
- Wait ;p

#### Screenshots (if possible):

Won't help in this case.

**Comment by zoff99** [comment]
please attach the debuglog.
goto "About" -> "send Crash repot via Email" right after the error happens

!!the file may contain personal information!!

**Comment by ghost** [comment]
Email sent but I think there was a new error because the map download fails too.

**Comment by ghost** [comment]
Solution:
- Go to App Info
- Click "Force Stop"
- "Storage"
- "Clear Cache"
- "Clear Data"
- Retry to download the map (+index)
