### ISSUE TITLE
Error on downloading Californa map.

### ISSUE THREAD

**Issue by John-Nagle** [zoff99/zanavi#27]
﻿#### Your system information:
ZANavi Version: 2.0.57

App from Google-Play / F-Droid / other: F-Droid

Android OS Version: 7.1.2

Device: Cat B31- new phone, powered up for the first time today.

#### Please describe your issue in as much detail as possible:
Attempts to download California map result in the notification "ZANavi - California ERROR" at the start of the download. Able to download Country Borders and US Pacific successfully. 

29GB of storage space is available on the SD card, where the maps are going, and over 1GB in phone storage. This isn't an out of space problem.

#### Steps for reproducing this issue:

- Start ZNAvi.
- Try to download California map data.

**Comment by zoff99** [comment]
@John-Nagle is this still not working?

**Comment by John-Nagle** [comment]
It seems to be working now.
