### ISSUE TITLE
ZANavi not available on Google Play Market anymore?

### ISSUE THREAD

**Issue by alex-kowalczyk** [zoff99/zanavi#29]
https://play.google.com/store/apps/details?id=com.zoffcc.applications.zanavi:
We're sorry, the requested URL was not found on this server.

Also cannot find the main app via Play search - only companion apps are available (donate & plugins).

**Comment by zoff99** [comment]
The app was kicked out of the playstore for accepting bitcoin donations.
you can get the latestet release here:
https://f-droid.org/en/packages/com.zoffcc.applications.zanavi/
